### ISSUE TITLE
ur_init模块，在ims_mc_members，增加 modifytime字段，每次客户改资料会更新该字段

### ISSUE THREAD

**Issue by guohuadeng** [guohuadeng/urWq#12]
ims_mc_members,  在init脚本里，做个增加 modifytime字段  ALTER TABLE  `ims_mc_members` ADD  `modifytime` INT(10)  UNSIGNED  NOT NULL AFTER  `createtime` ; 
然后每次当客户改资料时，把这个 modifytime设置成当前时间，改资料的涉及页面有
/web/index.php?c=mc&a=member&do=post&uid=xx
/app/index.php?i=4&c=mc&a=profile&
/app/index.php?i=4&c=mc&a=bond&do=mobile&

**Comment by MillieZhang** [comment]
只有修改手机号的时候要改？

**Comment by MillieZhang** [comment]
#12（1/3）  然后每次当客户改资料时，把这个 modifytime设置成当前时间，改资料的涉及页面有
/app/index.php?i=4&c=mc&a=profile&
