### ISSUE TITLE
todo-zhang:开发一个模块，叫ur_init的，主要是初始化ur相关的数据库

### ISSUE THREAD

**Issue by guohuadeng** [guohuadeng/urWq#6]
检查 ims_mc_members 表是否有 jd_account字段（京东帐号），如果没有，则增加 varchar 30
检查 ims_mc_members 表是否有 modifytime字段（最后变更时间），如果没有，则增加 int 
检查 ims_profile_fields 表中是否有一条记录 field='jd_account'，如果没有，则增加这条记录，执行 

INSERT INTO `ims_profile_fields` VALUES ('37', 'jd_account', '1', '京东帐号', '', '0', '0', '0', '1');

**Comment by MillieZhang** [comment]
……我放的文件没有更新到系统里，你瞅瞅……

**Comment by guohuadeng** [comment]
检查 ims_users_profile 表是否有 jd_account字段（京东帐号），如果没有，则增加 varchar 30
检查 ims_mc_members 表是否有 jd_account字段（京东帐号），如果没有，则增加 varchar 30
检查 ims_mc_members 表是否有 modifytime字段（最后变更时间），如果没有，则增加 int 
检查 ims_profile_fields 表中是否有一条记录 field='jd_account'，如果没有，则增加这条记录，执行

INSERT INTO ims_profile_fields VALUES ('37', 'jd_account', '1', '京东帐号', '', '0', '0', '0', '1');
