### ISSUE TITLE
todo:zhang - mc.mod.php的改造及bug修复

### ISSUE THREAD

**Issue by guohuadeng** [guohuadeng/urWq#7]
针对增加的 jd_account，更新数据库操作
修改生日变更存在问题的bug
做完后进行一次会员中心注册的检查
在会员卡管理里删除已注册的会员卡，再注册
http://wq.sunpop.cn/web/index.php?c=mc&a=card&do=manage&

**Comment by MillieZhang** [comment]
我需要操作一些文件，请尽量把所有文件都放到版本控制里来
